name: MTVehicles
version: 1.2.1
main: nl.gamerjoep.vehicles.Main
author: GamerJoep_
depend: [ProtocolLib]
commands:
  minetopiavehicles:
    usage: "/minetopiavehicles"
    aliases:
    - "mtv"
    - "mtvehicles"
    - "vehicle"
